teams:
  names:
    - "Red"
    - "Green"
    - "Blue"
    - "Yellow"
    - "Black"
  colors:
    - "RED"
    - "GREEN"
    - "BLUE"
    - "YELLOW"
    - "BLACK"
drop_rates:
    APPLE: 0
    GOLDEN_APPLE: 0
    FLINT: 0
    FEATHER: 0
    ARROW: 0
    XP_BOTTLE: 0
    ENDER_PEARL: 0